### ISSUE TITLE
Push tags for api/<v>

### ISSUE THREAD

**Issue by randomvariable** [vmware-tanzu/vm-operator#194]
**Please describe the solution you would like.**

Because /api has it's own go.mod, for consuming codebases (e.g. Cluster API vSphere) to consume a git tag of `/api` requires a tag to be published for `api/<version>`, ideally at the same commit as for the `<version>` tag.

**Comment by akutz** [comment]
I'm not exactly sure how to do this. I've noticed it before due to [pkg.go.dev](http://pkg.go.dev/). Tags show up as expected for https://pkg.go.dev/github.com/vmware-tanzu/vm-operator, but not for the module https://pkg.go.dev/github.com/vmware-tanzu/vm-operator/api. If you know how to do this, I'm all ears.

**Comment by akutz** [comment]
I found it at https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories, thanks @randomvariable !
