### ISSUE TITLE
vmop: Check CPU and memory are set on VM during UpdateConfigSpec 

### ISSUE THREAD

**Issue by srajashekar-vmw** [vmware-tanzu/vm-operator#44]
[UpdateConfigSpec](https://github.com/vmware-tanzu/vm-operator/blob/45c7a1e861db51ff0ce5e3cff0862288a0a3e960/pkg/vmprovider/providers/vsphere/session/session_vm_update.go#L449-L466) over writes CPU / Memory reservations from the ConfigSpec even if it is set on the VM.

[UpdateConfigSpecAllocation](https://github.com/vmware-tanzu/vm-operator/blob/45c7a1e861db51ff0ce5e3cff0862288a0a3e960/pkg/vmprovider/providers/vsphere/session/session_vm_update.go#L233-L294) needs to validate if the CPU and memory allocation is set on the VM before overwriting the values from ConfigSpec
in the update workflow as we do not want the changes updated to VMClass to reflect on the VM once the VM is created.

**Comment by aruneshpa** [comment]
Before the VM is powered on, we try to reconfigure the VM which also takes the VM class into account.  So if the class was modified to have a different hardware spec or resource reservations, those will be applied as part of the Reconfigure.  So, this is behaving as expected?  This may not be the _correct_ behavior (since it results in VM getting updated), but it will be a behavior change if we decide to address this.

Did I misunderstand the issue?
