### ISSUE TITLE
ci: The testing-needed labels appear to not always work

### ISSUE THREAD

**Issue by akutz** [vmware-tanzu/vm-operator#73]
I've noticed the `testing-needed` labels are not working as intended. For example, on https://github.com/vmware-tanzu/vm-operator/pull/72 the label did not cause the PR check to fail until I removed and then re-added the label manually. PR https://github.com/vmware-tanzu/vm-operator/pull/71 is a good example of where the label is present, but it is not blocking the PR. 

@dilyar8, can you PTAL at this? Thanks!

**Comment by dilyar85** [comment]
The issue occurred because the `testing-needed` workflow was executed prior to the `pr-labeler` workflow, where the PR did not have the testing-needed-full/fast label attached yet. As a result, the do-not-merge step didn't run which led to the PR check not failing. The above PR fixes it by using the [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) event type to enforce their execution order.

**Comment by dilyar85** [comment]
After doing some testing, I realized that the above "workflow_run" event type didn't work because the "testing-needed" workflow uses `github.event.*.labels.*.name` to check labels on a pull request. I also tried moving it into the "pr-labeler" workflow and applying a `needs: add-labels` statement but found that the `github.event.*.labels.*.name` would not contain the updated labels from the `add-labels` job.

I ended up having the "testing-needed" workflow to get triggered only when labels are changed on a PR. And I updated the "pr-labelers" workflow to use a separate GitHub token so that it can trigger other workflows once completes (see [triggering a workflow from a workflow doc](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) for more details).
